# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PleaseWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PleaseWork

 pod 'Firebase/Auth'
 pod 'Firebase/Storage'
 pod 'Firebase/Firestore'
 pod 'URLImage'


  target 'PleaseWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PleaseWorkUITests' do
    # Pods for testing
  end

end
